name: 'Apply Tagging'

on:
  workflow_call:
    inputs:
      RUNNER_LABEL:
        required: true
        type: string
      ENVIRONMENT:
        required: false
        default: prod
        type: string
      APP_NAME:
        required: true
        type: string
      INFRASTRUCTURE_FOLDER:
        required: false
        default: "infrastructure"
        type: string
      IMAGE_TAG:
          type: string
          required: false
      SERVICE:
          required: false
          type: string

    secrets:
      AWS_GITHUBRUNNER_PAT:
        required: true
      AWS_GITHUBRUNNER_PAT_USER:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  stop-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Tag built image with deployment environment
        env:
          ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
          APP_NAME: ${{ inputs.APP_NAME }}
          INFRASTRUCTURE_FOLDER: ${{ inputs.INFRASTRUCTURE_FOLDER }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
          SERVICE: ${{ inputs.SERVICE }}
        run: |
          if [[ $INFRASTRUCTURE_FOLDER ]]; then
            cd main
            if [[ $IMAGE_TAG ]]; then
              make docker_update_tag tag=$ENVIRONMENT IMAGE_TAG=$IMAGE_TAG
            else
              make docker_update_tag tag=$ENVIRONMENT service=$SERVICE
            fi
          fi