name: Update repository from Cookiecutter

on:
  workflow_call:
    secrets:
      AWS_GITHUBRUNNER_PAT:
        required: true
  
jobs:
  check_existing_prs:
    runs-on: ubuntu-latest
    outputs:
      both_prs_already_open: ${{ steps.check_prs_open.outputs.result }}
    steps:
      - name: Check if Accept & Reject PRs already open
        uses: actions/github-script@v7
        id: check_prs_open
        with:
          result-encoding: string
          retries: 2
          script: |
            const openPullReqs = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open'
            });

            let detectedAcceptPR = false;
            let detectedRejectPR = false;

            openPullReqs.data.forEach(pr => {
              if (pr.title.includes("accept-pr")) {
                console.log(pr.html_url);
                detectedAcceptPR = true;
              }
              if (pr.title.includes("reject-pr")) {
                console.log(pr.html_url);
                detectedRejectPR = true;
              }
            });

            result = detectedAcceptPR && detectedRejectPR;
            console.log(`Accept and Reject PRs already open: ${result}`);
            return result;

  update:
    if: needs.check_existing_prs.outputs.both_prs_already_open == 'false'
    needs:
      - check_existing_prs
    name: ${{ matrix.type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - type: accept-pr
            add-paths: .
            body: Use this PR to merge the detected changes into this repository.
            branch: cruft/update
            commit-message: "chore: accept new Cruft update"
            title: cruft - Accept detected infrastructure changes
          - type: reject-pr
            add-paths: .cruft.json
            body: Use this PR to reject the detected changes into this repository.
            branch: cruft/reject
            commit-message: "chore: reject new Cruft update"
            title: cruft - Reject detected infrastructure changes
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set global git credentials
        run: git config --global url.https://${{ secrets.AWS_GITHUBRUNNER_PAT }}@github.com/.insteadOf https://github.com/

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Cruft
        run: pip3 install cruft

      - name: Check if update is available
        continue-on-error: false
        id: check
        run: |
          CHANGES=0
          if [ -f .cruft.json ]; then
            if ! cruft check --checkout EN-669/cruft_action; then
              CHANGES=1
            fi
          else
            echo "No .cruft.json file"
          fi

          echo "has_changes=$CHANGES" >> "$GITHUB_OUTPUT"

      - name: Run update if available
        if: steps.check.outputs.has_changes == '1'
        run: |
          cruft update --skip-apply-ask --refresh-private-variables --checkout EN-669/cruft_action
          git restore --staged .

      - name: Create pull request
        if: steps.check.outputs.has_changes == '1'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: ${{ matrix.add-paths }}
          commit-message: ${{ matrix.commit-message }}
          branch: ${{ matrix.branch }}
          delete-branch: true
          branch-suffix: timestamp
          title: ${{ matrix.title }} (${{ matrix.type }})
          body: |
            This is an autogenerated PR created to keep this repository in line with the base Cookiecutter template. 
            
            Changes have been detected in the base template and they should be considered for merging.
            
            ${{ matrix.body }}

            If this PR is merged, its corresponding accept/reject PR (which was raised at the same time) should be closed without merging it.
            
            See the README/guides in the [Cookiecutter](https://github.com/i-dot-ai/i-dot-ai-cookiecutter/README.md), or contact the infrastructure team for further guidance.
