name: Reset User

on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      RUNNER_LABEL:
        required: true
        type: string
      ENVIRONMENT:
        required: false
        default: prod
        type: string
      # CORE_INFRA_REF:
      #   type: string
      #   required: false
      #   default: refs/heads/main
      # INFRA_CONFIG_REF:
      #   type: string
      #   required: false
      #   default: refs/heads/main
      # IMAGE_TAG:
      #   type: string
      #   required: false
      EMAIL_ADDRESS:
          type: string
          required: true
      USE_OIDC:
          type: string
          required: false

    secrets:
      AWS_GITHUBRUNNER_PAT:
        required: true
      AWS_GITHUBRUNNER_PAT_USER:
        required: true
      AWS_REGION:
        required: true
      AWS_ACCOUNT_ID:
        required: true

jobs:
  reset-user:
    runs-on: ${{ inputs.RUNNER_LABEL }}
    environment: ${{ inputs.ENVIRONMENT }}

    permissions:
      id-token: write
      contents: read

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: main

    - name: Set global git credentials
      run: git config --global url.https://${{ secrets.AWS_GITHUBRUNNER_PAT }}@github.com/.insteadOf https://github.com/

    - name: Dump Inputs Context
      env:
        INPUTS: ${{ toJSON(inputs) }}
      run: echo "$INPUTS"

    - name: AWS Authentication
      uses: i-dot-ai/i-dot-ai-core-github-actions/.github/actions/authenticate-aws@main
      with:
        USE_OIDC: ${{ inputs.USE_OIDC }}
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        AWS_GITHUBRUNNER_USER_ACCESS_KEY: ${{ secrets.AWS_GITHUBRUNNER_USER_ACCESS_KEY }}
        AWS_GITHUBRUNNER_USER_SECRET_ID: ${{ secrets.AWS_GITHUBRUNNER_USER_SECRET_ID }}

    - name: Check AWS Auth
      shell: bash
      run: aws sts get-caller-identity

    # - name: Checkout i-ai-core-infrastructure
    #   uses: actions/checkout@v4
    #   with:
    #     repository: i-dot-ai/i-ai-core-infrastructure
    #     ref: ${{ inputs.CORE_INFRA_REF }}
    #     token: ${{ secrets.AWS_GITHUBRUNNER_PAT }}
    #     path: i-ai-core-infrastructure


    - name: Checkout
      uses: actions/checkout@v4
      with:
          path: main


    - name: Terraform init
      env:
        ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      run: |
        cd main
        make tf_init env=${{ inputs.ENVIRONMENT }}